name: PHP

on:
  push:
  workflow_dispatch:

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@2.18.1
        with:
          coverage: none
          php-version: '7.4'

      - uses: shivammathur/setup-php@2.18.1
        with:
          coverage: none
          php-version: '8.0'

      - run: ls -lha /usr/bin

      - run: sudo update-alternatives --set php "/usr/bin/php7.4"
      - run: php -v

      - run: sudo update-alternatives --set php "/usr/bin/php8.0"
      - run: php -v
