name: Run build job only once

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      head_tag: ${{ steps.check.outputs.head_tag }}
      foreign_pr: ${{ steps.check.outputs.foreign_pr }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Retrieve tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Set output variables
        id: check
        run: |
          fpr="no"
          tag=""
          if [[ "${{ github.ref }}" == refs/heads/* ]]; then
            tag="$(git tag --points-at HEAD)"
          elif [[ "${{ github.ref }}" == refs/pull/* ]] && [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.event.pull_request.base.repo.full_name }}" ]; then
            fpr="yes"
          fi
          echo "FPR: ${fpr}"
          echo "TAG: ${tag}"
          echo "${{ github.event_name }}"
          echo "::set-output name=foreign_pr::${fpr}"
          echo "::set-output name=head_tag::${tag}"

  build:
    runs-on: ubuntu-latest
    needs: prepare
    if: "(github.event_name == 'push' && needs.prepare.outputs.head_tag == '') || (github.event_name == 'pull_request' && needs.prepare.foreign_pr == 'yes')"
    steps:
      - run: echo Hello
