name: On Workflow Run

on:
  workflow_run:
    types:
      - "completed"
    workflows:
      - "Debug"

jobs:
  debug:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    steps:
      - run: env
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
